-- Version the commercial backend in one place. Browser clients use Supabase
-- Auth only; private product data is accessed through authenticated Next.js
-- routes with the server-only service role credential.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  stripe_customer_id text,
  stripe_subscription_id text,
  subscription_status text not null default 'inactive',
  price_id text,
  current_period_end timestamptz,
  stripe_event_created_at bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.donations (
  id bigint generated by default as identity primary key,
  stripe_session_id text not null,
  amount_total bigint,
  currency text,
  payment_status text,
  created_at timestamptz not null default now()
);

create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  message text not null,
  email text,
  created_at timestamptz not null default now()
);

-- Make the migration safe for the existing project as well as a fresh one.
alter table public.profiles add column if not exists email text;
alter table public.profiles add column if not exists stripe_customer_id text;
alter table public.profiles add column if not exists stripe_subscription_id text;
alter table public.profiles add column if not exists subscription_status text default 'inactive';
alter table public.profiles add column if not exists price_id text;
alter table public.profiles add column if not exists current_period_end timestamptz;
alter table public.profiles add column if not exists stripe_event_created_at bigint;
alter table public.profiles add column if not exists created_at timestamptz default now();
alter table public.profiles add column if not exists updated_at timestamptz default now();

alter table public.donations add column if not exists stripe_session_id text;
alter table public.donations add column if not exists amount_total bigint;
alter table public.donations add column if not exists currency text;
alter table public.donations add column if not exists payment_status text;
alter table public.donations add column if not exists created_at timestamptz default now();

alter table public.feedback add column if not exists message text;
alter table public.feedback add column if not exists email text;
alter table public.feedback add column if not exists created_at timestamptz default now();

-- Constraints reject malformed server writes before they become durable data.
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'profiles_email_length_check'
      and conrelid = 'public.profiles'::regclass
  ) then
    alter table public.profiles
      add constraint profiles_email_length_check
      check (email is null or char_length(email) <= 320) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'profiles_subscription_status_check'
      and conrelid = 'public.profiles'::regclass
  ) then
    alter table public.profiles
      add constraint profiles_subscription_status_check
      check (
        subscription_status is null or subscription_status in (
          'inactive', 'incomplete', 'incomplete_expired', 'trialing', 'active',
          'past_due', 'canceled', 'unpaid', 'paused'
        )
      ) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'donations_amount_total_check'
      and conrelid = 'public.donations'::regclass
  ) then
    alter table public.donations
      add constraint donations_amount_total_check
      check (amount_total is null or amount_total >= 0) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'donations_currency_check'
      and conrelid = 'public.donations'::regclass
  ) then
    alter table public.donations
      add constraint donations_currency_check
      check (currency is null or currency ~ '^[a-z]{3}$') not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'feedback_message_length_check'
      and conrelid = 'public.feedback'::regclass
  ) then
    alter table public.feedback
      add constraint feedback_message_length_check
      check (message is not null and char_length(message) between 10 and 2000) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'feedback_email_length_check'
      and conrelid = 'public.feedback'::regclass
  ) then
    alter table public.feedback
      add constraint feedback_email_length_check
      check (email is null or char_length(email) <= 320) not valid;
  end if;
end $$;

create unique index if not exists profiles_stripe_customer_id_uidx
  on public.profiles (stripe_customer_id);
create unique index if not exists profiles_stripe_subscription_id_uidx
  on public.profiles (stripe_subscription_id);
create unique index if not exists donations_stripe_session_id_uidx
  on public.donations (stripe_session_id);
create index if not exists profiles_active_subscription_idx
  on public.profiles (subscription_status, current_period_end)
  where subscription_status in ('active', 'trialing');
create index if not exists donations_created_at_idx on public.donations (created_at desc);
create index if not exists feedback_created_at_idx on public.feedback (created_at desc);

-- Create the private profile row at auth-user creation time. The empty search
-- path and fully qualified names prevent SECURITY DEFINER name-shadowing.
create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, email, updated_at)
  values (new.id, new.email, now())
  on conflict (id) do update
    set email = excluded.email,
        updated_at = excluded.updated_at;
  return new;
end;
$$;

revoke execute on function private.handle_new_user() from public, anon, authenticated;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function private.handle_new_user();

-- Defense in depth: even if a public client key is copied, it has no direct
-- access to private application tables. The service role remains server-only.
alter table public.profiles enable row level security;
alter table public.profiles force row level security;
alter table public.donations enable row level security;
alter table public.donations force row level security;
alter table public.feedback enable row level security;
alter table public.feedback force row level security;
alter table public.workspace_documents enable row level security;
alter table public.workspace_documents force row level security;

revoke all on table public.profiles, public.donations, public.feedback, public.workspace_documents
  from anon, authenticated;
grant select, insert, update, delete
  on table public.profiles, public.donations, public.feedback, public.workspace_documents
  to service_role;

comment on table public.profiles is 'Server-managed account and Stripe entitlement state.';
comment on table public.donations is 'Idempotent Stripe Checkout records for one-off support payments.';
comment on table public.feedback is 'User-submitted product feedback with an optional reply address.';
